import { Suspense } from "react";
import Header from "./components/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
import Loading from "./loading";
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "500", "700"],
    variable: "--font-poppins",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="cupcake" className="font-poppins">
            <head>
                <link
                    rel="stylesheet"
                    as="style"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
                />
            </head>
            <body className={poppins.className}>
                <Header />
                <Suspense fallback={<Loading />}>{children}</Suspense>
            </body>
        </html>
    );
}
